version: '3.3'

services:
  frontend:
    build: .
    volumes:
      - frontend-build_volume:/app/build
    command: npm run build --prod

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - frontend-build_volume:/usr/share/nginx/html
    depends_on:
      - frontend

volumes:
  frontend-build_volume: